<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Antoxa
 * Date: 04.06.13
 * Time: 13:27
 */
namespace Flint\Security\Service\OAuth;

use OAuth\OAuth2\Service\AbstractService as parentOauth2AbsctactService;

abstract class OAuth2AbstractService extends parentOauth2AbsctactService implements OAuthUserResultInterface{

    public function request($path, $method = 'GET', $body = null, array $extraHeaders = array())
    {
        $this->modifyRequestPath($path);
        return parent::request($path, $method, $body, $extraHeaders); // TODO: Change the autogenerated stub
    }

    protected function modifyRequestPath(&$path){}

    public function getResultUid($result){
        return $result['id'];
    }

    public function getResultEmail($result){
        return isset($result['email'])?$result['email']:false;
    }

    public function requestUserInfo($path)
    {
        $result = json_decode($this->request($path), true);
        $_SESSION['oauth_user_info'] = $result;

        return $result;
    }

    public function getUserData($result = null)
    {
        $data = $this->_getUserData();
        return $data;
    }

    function _getUserData()
    {
        return array();
    }


}